# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Usage
  items:
    - label: 'API Gateway'
      link: 'api-gateway'
    - label: 'Custom Connectors'
      link: 'custom-connectors'
- label: 'More'
  items:
    - label: 'TeamCentral.ai'
      link: 'https://teamcentral.ai'